lxc/lxc-ci

templates/sabayon.json
=> [sabayon] Fix use of armv7l arch and setting of ssh service through systemd

bin/test-lxd-docker
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
=> docker: amd64 -> x86_64

bin/test-lxd-docker
Two things:
1. Quiet wget
2. Show `docker info`
=> test-lxd-docker improvements

lxc_ci/__init__.py
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>
=> lxc_ci: Fix support for LXC 3.0

images/ubuntu-core/init
=> images: Fix Ubuntu Core 18 init

images/gentoo.yaml
=> images: Do not create TTYs on Gentoo

images/opensuse.yaml, jenkins/includes/snap-distros.yaml.inc, jenkins/jobs/image-opensuse.yaml
=> Clean up openSUSE 42.3 leftovers

bin/build-lxd
Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>
=> Enable sqlite/dqlite multi-thread support when running unit tests

images/voidlinux.yaml, jenkins/jobs/image-voidlinux.yaml
=> Add Void Linux

jenkins/jobs/lxc-github-commit.yaml
=> jenkins: Run trigger builds only once

images/plamo.yaml
=> images: Fix Plamo post unpack

images/debian.yaml, jenkins/jobs/image-debian.yaml
* Mark Debian buster as stable
* Add Debian bullseye
See https://github.com/lxc/distrobuilder/issues/218
=> Add Debian bullseye

jenkins/jobs/image-alpine.yaml, jenkins/jobs/image-debian.yaml, jenkins/jobs/image-devuan.yaml, jenkins/jobs/image-opensuse.yaml
=> jenkins/jobs: Add missing variant image option

jenkins/jobs/image-openwrt.yaml
=> jobs: Add OpenWrt 18.06

images/apertis.yaml
=> images: Fix IPV4 on Apertis

bin/update-images
=> update-images: Add patch to distrobuilder

bin/update-images
=> update-images: Install build-essential

bin/update-images
=> update-images: Install gawk

bin/update-images
=> update-images: Install libncurses-dev

images/opensuse.yaml
=> images: Fix cloud-init on openSUSE

images/opensuse.yaml
=> images: Fix cloud-init for openSUSE Leap

bin/update-images
=> update-images: Install unzip

jenkins/jobs/image-centos.yaml
=> jenkins/jobs: Add CentOS 8

images/centos.yaml
=> images: Add PGP key for CentOS 8

jenkins/jobs/image-fedora.yaml
Signed-off-by: Anatoli Babenia <anatoli@rainforce.org>
=> Add Fedora 31 for testing

images/oracle.yaml, jenkins/jobs/image-oracle.yaml
This is blocked by https://github.com/lxc/distrobuilder/pull/252.
=> Add Oracle Linux 8

images/openwrt.yaml
=> images/openwrt: Add new GPG key

images/centos.yaml, jenkins/jobs/image-centos.yaml
This depends on https://github.com/lxc/distrobuilder/pull/268.
=> Add CentOS Stream 8

images/debian.yaml, jenkins/jobs/image-debian.yaml
=> images: Add Debian VM support

images/debian.yaml
=> images/debian: Fix VM image for Debian Jessie

images/fedora.yaml
=> images/fedora: Fix root= kernel cmdline

images/fedora.yaml
=> images/fedora: Fix grub.cfg

images/fedora.yaml
=> images/fedora: Fix networking for VMs

images/gentoo.yaml
=> images/gentoo: Fix type filter in post actions

images/opensuse.yaml
=> images/opensuse: Add check for shim-install

images/centos.yaml
=> images/centos: Template DHCP_HOSTNAME

images/centos.yaml, jenkins/jobs/image-centos.yaml
=> images/centos: Add CentOS VM support

jenkins/jobs/image-centos.yaml
=> jenkins/jobs: Disable CentOS VMs on ARM

images/centos.yaml
=> images/centos: Add /sys/firmware workaround for VMs

images/pld.yaml, jenkins/jobs/image-pld.yaml
PLD (https://pld-linux.org/) LXD/LXC image. Tested with bin/build-distro script, but I'm not 100% sure about Jenkins job.
=> Add PLD Linux

images/opensuse.yaml
=> images/opensuse: Fix VM network

images/mint.yaml, images/ubuntu.yaml
=> Use mac address as identifier

bin/test-lxd-ovn
- Tests creating OVN network of same name and subnet in default and test project.
- Tests in-use deletion protection of OVN networks and referenced parent networks.
- Tests OVN network deletion.
=> OVN Projects

jenkins/jobs/image-apertis.yaml
=> jenkins/jobs: Update Apertis releases

images/plamo.yaml
This is the equivalent of https://github.com/lxc/lxc-templates/commit/551f56b5d529ced1b6b51206c4e9b7055e338028
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>
=> images/plamo: fix for current Plamo 7.x

bin/test-lxd-ovn
=> bin/test-lxd-ovn: Adds test for passing external IP subnet into network

bin/test-lxd-cluster
=> bin/test-lxd-cluster: Adds cluster fan networking tests

bin/test-lxd-vm
Depends on https://github.com/lxc/lxd/pull/8225
=> bin/test-lxd-vm: Adds ceph support and uses random pool name

bin/test-lxd-ovn
Depends on https://github.com/lxc/lxd/pull/8226
=> Network: Adds OVN routed ingress mode tests

bin/test-lxd-ovn
Depends on https://github.com/lxc/lxd/pull/8229
=> bin/test-lxd-ovn: Adds tests for DHCP disabling

bin/test-lxd-ovn
Depends onhttps://github.com/lxc/lxd/pull/8233
=> bin/test-lxd-ovn: Adds routed ingress anycast tests

bin/test-lxd-ovn
Tests for https://github.com/lxc/lxd/pull/8262
=> bin/test-lxd-ovn: Adds tests for using a physical bridge uplink

bin/test-lxd-ovn
=> bin/test-lxd-ovn: Fix tests in environments with multiple bridges

bin/test-lxd-ovn
Depends on https://github.com/lxc/lxd/pull/8307
=> bin/test-lxd-ovn: Adds checks for uplink settings being propagated to dependent networks and NICs

bin/test-lxd-vm
=> bin/test-lxd-vm: Adds rename test

jenkins/includes/admins/pylxd.yaml.inc
Signed-off-by: Adam Collard <adam.collard@canonical.com>
=> Remove d0ugal from pylxd maintainership

images/archlinux.yaml, jenkins/jobs/image-archlinux.yaml
=> Add cloud-init support for Arch Linux

bin/test-lxd-ovn, bin/test-lxd-ovn-acl
Requires https://github.com/lxc/lxd/pull/8447
=> Network: OVN ACL tests

bin/test-lxd-ovn-acl
Tests for feature added in https://github.com/lxc/lxd/pull/8495
=> Network: OVN ACL tests for #internal and #external subjects

jenkins/jobs/lxd-test-ovn-acl.yaml
=> jenkins: Adds lxd-test-ovn-acl job

bin/test-lxd-ovn-acl
Requires https://github.com/lxc/lxd/pull/8581
=> Network: OVN ACL per-NIC default rules

bin/test-lxd-cluster
=> lxd-test-cluster: Print lxd logs at end of test

jenkins/jobs/lxd-test-storage-vm.yaml
=> jobs: Rename lxd-test-storage to lxd-test-storage-vm to match file name and description

images/almalinux.yaml, jenkins/jobs/image-almalinux.yaml
Related AlmaLinux OS issue: AlmaLinux/cloud-images#8.
=> Adds AlmaLinux OS support (fixes #302)

images/opensuse.yaml, jenkins/jobs/image-opensuse.yaml
- images: Add openSUSE 15.3
- jenkins/jobs: Add openSUSE 15.3
=> Add openSUSE Leap 15.3

images/almalinux.yaml
=> images/almalinux: Add hostname package

images/almalinux.yaml, images/centos.yaml, images/sabayon.yaml
=> images: Remove systemd fixes

images/almalinux.yaml, images/rockylinux.yaml, images/springdalelinux.yaml
- images/almalinux: Switch to network-scripts
- images/rockylinux: Switch to network-scripts
- images/springdalelinux: Switch to network-scripts
=> images: Switch RHEL/CentOS derivates to network-scripts

images/almalinux.yaml
=> images/almalinux: Add openssh-server to cloud images

images/springdalelinux.yaml
=> springdalelinux: Add openssh-server to cloud images

images/springdalelinux.yaml
=> images/springdalelinux: Add hostname package

jenkins/jobs/image-alt.yaml, jenkins/jobs/image-centos.yaml, jenkins/jobs/image-fedora.yaml, jenkins/jobs/image-gentoo.yaml, jenkins/jobs/image-opensuse.yaml, jenkins/jobs/image-oracle.yaml, jenkins/jobs/image-pld.yaml, jenkins/jobs/image-springdalelinux.yaml
=> Review architectures

images/rockylinux.yaml
=> images/rockylinux: Add hostname package

jenkins/jobs/image-alpine.yaml
=> jenkins/jobs: Add Alpine 3.14

bin/test-lxd-migration, images/ubuntu.yaml, jenkins/jobs/image-ubuntu.yaml, jenkins/jobs/lxd-test-pylxd.yaml
=> Drop Trusty that is EOL

jenkins/jobs/image-amazonlinux.yaml, jenkins/jobs/image-apertis.yaml
- jenkins/jobs: Update Amazon Linux version
- jenkins/jobs: Update Apertis version
=> Image review

jenkins/jobs/image-centos.yaml
=> jenkins/jobs: Fix CentOS builds

jenkins/jobs/image-centos.yaml
=> jenkins/jobs: Fix centOS args

bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn-acl, jenkins/jobs/lxd-test-network-bridge-firewall.yaml
Tests using snap with nftables and xtables drivers.
=> Network: Adds bridge firewall tests

bin/test-lxd-cluster
=> lxd-test-cluster: Increase wait time after upgrade

images/mint.yaml, images/ubuntu-core.yaml, images/ubuntu.yaml, jenkins/jobs/lxc-build-ubuntu-source.yaml
And stop building sources for Ubuntu 16.04
=> Drop support for Ubuntu 14.04

images/mint.yaml, jenkins/jobs/image-mint.yaml
- images: Add Linux Mint 20.2 (Uma)
- jenkins/jobs: Add Linux Mint 20.2 (Uma)
=> Add Linux Mint 20.2 ("Uma")

jenkins/jobs/image-gentoo.yaml
=> jenkins/jobs: Add Gentoo systemd variant

jenkins/jobs/image-mint.yaml
=> jenkins/jobs: Fix Linux Mint 20.2 ("Uma")

images/gentoo.yaml
=> images: Fix gentoo systemd VM

jenkins/jobs/lxd-test-cluster.yaml
=> lxd-test-cluster: Update previous LXD to 4.15

images/gentoo.yaml
=> images: Fix gentoo networking on systemd variant

images/voidlinux.yaml
=> images: Override mirror URL for voidlinux

images/fedora.yaml
=> images: Fix Fedora grub.cfg

images/archlinux.yaml
=> images: Add openssh to Arch Linux/cloud

images/voidlinux.yaml
=> images: Fix repo URL for voidlinux/aarch64

bin/test-lxd-images, images/busybox.yaml, jenkins/jobs/images-busybox.yaml
- images: Add busybox
- jenkins/jobs: Add busybox
- test-lxd-images: Skip busybox
=> Add busybox

jenkins/jobs/images-busybox.yaml
=> jenkins/jobs: Fix busybox

images/ubuntu.yaml, jenkins/jobs/image-ubuntu.yaml
- jenkins/jobs: Remove Ubuntu Groovy (EOL)
- images: Remove Ubuntu Groovy traces
=> Remove Ubuntu Groovy (EOL)

images/fedora.yaml
- images: Fix grub in Fedora VMs
- images: Merge post-files actions for Fedora VMs
=> Fix Fedora VMs

images/almalinux.yaml, images/alpine.yaml, images/alt.yaml, images/amazonlinux.yaml, images/apertis.yaml, images/archlinux.yaml, images/centos.yaml, images/debian.yaml, images/devuan.yaml, images/fedora.yaml, images/funtoo.yaml, images/gentoo.yaml, images/kali.yaml, images/mint.yaml, images/opensuse.yaml, images/openwrt.yaml, images/oracle.yaml, images/plamo.yaml, images/pld.yaml, images/rockylinux.yaml, images/sabayon.yaml, images/springdalelinux.yaml, images/ubuntu.yaml, images/voidlinux.yaml
=> images: Add sudo package

bin/test-lxd-network-ovn
To allow ARP/NDP resolution onto bridge.
=> bin/test-lxd-network-ovn: Increase ping timeouts

images/plamo.yaml
package manager for plamo is updated.
Signed-off-by: KATOH Yasufumi <karma@jazz.email.ne.jp>
=> images: Support new plamo pkgtools8

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/9108
=> Network: Adds OVN forwards tests

jenkins/jobs/image-fedora.yaml
=> jenkins/jobs: Add Fedora 35

bin/build-distro
=> bin/build-distro: Fix springdalelinux build

jenkins/jobs/image-openwrt.yaml
=> jenkins/jobs: Add OpenWrt 21.02

images/alt.yaml
=> images/alt: Format yaml

images/almalinux.yaml, images/alpine.yaml, images/alt.yaml, images/amazonlinux.yaml, images/apertis.yaml, images/archlinux.yaml, images/busybox.yaml, images/centos.yaml, images/debian.yaml, images/devuan.yaml, images/fedora.yaml, images/funtoo.yaml, images/gentoo.yaml, images/kali.yaml, images/mint.yaml, images/opensuse.yaml, images/openwrt.yaml, images/oracle.yaml, images/plamo.yaml, images/pld.yaml, images/rockylinux.yaml, images/sabayon.yaml, images/springdalelinux.yaml, images/ubuntu-core.yaml, images/ubuntu.yaml, images/voidlinux.yaml
- images: Fix custom_manager key
- images: Fix create_message key
=> Fix yaml keys

images/opensuse.yaml
I don't know for sure if that'll fix it, but let's give it a try.
=> images/opensuse: Drop Tumbleweed ppc64le specific config

images/apertis.yaml, images/voidlinux.yaml
- images/apertis: Fix certificate issue
- images/voidlinux: Fix certificate issue
=> Fix certificate issues

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/9465
=> bin/test-lxd-network-ovn: Adds OVN peer ACL tests

bin/test-lxd-network-routed, jenkins/jobs/lxd-test-network-routed.yaml
Requires https://github.com/lxc/lxd/pull/9529
=> bin/test-lxd-network-routed: Adds routed NIC VM test

images/alpine.yaml
=> images: Add openssh to Alpine cloud images

bin/test-lxd-storage-vm
Tests to accompany https://github.com/lxc/lxd/pull/9565
=> VM: Check snapshot copy

bin/test-lxd-storage-disks-vm, jenkins/jobs/lxd-test-storage-disks-vm.yaml
Requires https://github.com/lxc/lxd/pull/9571
=> bin/test-lxd-storage-disks-vm: Adds restricted disk tests for VMs

bin/test-lxd-cgroup, bin/test-lxd-gpu-container, bin/test-lxd-gpu-mig, bin/test-lxd-gpu-vm, bin/test-lxd-images, bin/test-lxd-interception, bin/test-lxd-kernel, bin/test-lxd-maas, bin/test-lxd-network, bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn, bin/test-lxd-network-ovn-acl, bin/test-lxd-network-routed, bin/test-lxd-network-sriov, bin/test-lxd-rbac, bin/test-lxd-storage-disks-vm, bin/test-lxd-storage-vm, bin/test-lxd-storage-volumes-vm, bin/test-lxd-usb
=> bin/test-lxd-*: smarter wait for snapd seeding

jenkins/jobs/image-alpine.yaml
=> jenkins/jobs: Add Alpine Linux 3.15

jenkins/jobs/image-gentoo.yaml
=> jenkins/jobs: Fix Gentoo yaml

images/openwrt.yaml
=> images: Fix dnsmasq issue on openwrt/snapshot

jenkins/jobs/image-gentoo.yaml
=> jenkins/jobs: Fix Gentoo script

images/alpine.yaml
=> images: Replace sudo with doas for Alpine 3.15 and edge

images/alpine.yaml
- images/alpine: Add logrotate
- images/alpine: Clean up apk cache
=> images/alpine: Add logrotate and clean up apk cache

jenkins/jobs/image-mint.yaml
=> jenkins/jobs: Add Mint 20.3 (Una)

jenkins/jobs/lxd-test-cluster.yaml
=> jenkins: Update previous LXD version

images/gentoo.yaml
- images/gentoo: Fix locale warnings
- images/gentoo: Fix networking for OpenRC VMs
=> Gentoo fixes

images/archlinux.yaml
=> images/archlinux: Fix ping capabilities

bin/test-lxd-network
Updates tests to take into account changes from https://github.com/lxc/lxd/pull/9967
=> Fix VM network agent.nic_config tests

jenkins/jobs/lxd-test-cluster.yaml
=> jenkins: Autodetect previous LXD version

images/ubuntu.yaml, jenkins/includes/snap-distros.yaml.inc, jenkins/jobs/image-ubuntu.yaml, jenkins/jobs/lxc-build-ubuntu-source.yaml
=> Drop Ubuntu 21.04 (EOL on January 2022)

bin/test-lxd-network, bin/test-lxd-network-sriov, bin/test-lxd-usb
So I can run it at home on my Intel I350 card :)
Also tested on lantea in MAAS.
=> Update LXD network sriov tests to support NICs with only 7 VFs

images/voidlinux.yaml, jenkins/jobs/image-voidlinux.yaml
- images/voidlinux: Switch mirror
- jenkins/jobs/voidlinux: Switch mirror
=> voidlinux: Switch mirror

jenkins/jobs/image-voidlinux.yaml
=> jenkins/jobs/voidlinux: Fix source URL

images/ubuntu.yaml
=> images/ubuntu: Disable automatic screensaver lock

jenkins/jobs/image-ubuntu.yaml
This reverts commit 6d56cbe9e91d1b8ff2e263e0c009aee35eaed0ee.
=> Revert "jenkins: Disable desktop on jammy for now"

bin/test-lxd-storage-vm
=> bin/test-lxd-storage-vm: Add disk hotplug tests

bin/test-lxd-cgroup, bin/test-lxd-gpu-container, bin/test-lxd-gpu-mig, bin/test-lxd-gpu-vm, bin/test-lxd-images, bin/test-lxd-interception, bin/test-lxd-maas, bin/test-lxd-network, bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn, bin/test-lxd-network-ovn-acl, bin/test-lxd-network-routed, bin/test-lxd-network-sriov, bin/test-lxd-performance, bin/test-lxd-pylxd, bin/test-lxd-rbac, bin/test-lxd-storage-disks-vm, bin/test-lxd-storage-vm, bin/test-lxd-storage-volumes-vm, bin/test-lxd-usb
OCD fix with a net negative line count ;)
=> bin: Simplify LXD deb removal

bin/test-lxd-storage-vm
Depends on https://github.com/lxc/lxd/pull/10202
=> VM: Restore ordering of storage hotplug tests and add cloud-init ISO hotplug test

images/alpine.yaml
=> images/alpine: Honor fstab

images/alt.yaml, images/apertis.yaml, images/opensuse.yaml, images/pld.yaml
- images/alt: Fix invalid key
- images/apertis: Fix invalid key
- images/opensuse: Fix invalid key
- images/pld: Drop invalid keys
=> Fix invalid yaml files

images/debian.yaml
=> images/debian: Image fixes

images/gentoo.yaml
=> images/gentoo: Mask systemd-binfmt.service

jenkins/jobs/image-fedora.yaml
=> jenkins/jobs/fedora: Add Fedora 36

images/fedora.yaml
- images/fedora: Use systemd-networkd for 36/cloud
- images/fedora: Link to stub-resolv.conf
=> Use systemd-networkd for 36/cloud

bin/test-lxd-storage-volumes-vm, jenkins/jobs/lxd-test-storage-volumes-vm.yaml
=> bin/test-lxd-storage-volumes-vm: Adds support for non-thin LVM pools

bin/test-lxd-network-ovn, jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml
Requires https://github.com/lxc/lxd/pull/10393
Closes https://github.com/lxc/lxc-ci/issues/490
=> test: Add Jammy support for OVN network tests

jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml
=> jenkins/jobs/lxd-test-network-ovn: Use Jammy correctly

images/fedora.yaml, jenkins/jobs/image-fedora.yaml
- images/fedora: Drop v34
- jenkins/jobs/fedora: v34 is EOL
- images/fedora: Update dnf settings
=> Fedora updates

jenkins/jobs/image-almalinux.yaml
=> images/almalinux: Add s390x architecture

images/fedora.yaml
=> images/fedora: Use fixed mirror

images/centos.yaml
=> images/centos: Use fixed mirror in build

images/centos.yaml
=> images/centos: Fix mirror for v7 non-x86_64

images/voidlinux.yaml
- images/voidlinux: Change repo URL
- images/voidlinux: Change repo before xbps update
=> images/voidlinux: Repo URL fixes

images/centos.yaml
=> images/centos: Fix 7/i386 repo

images/centos.yaml
This fixes the cloud-init network-config for all releases.
=> images/centos: Fix cloud-init network-config

images/debian.yaml, jenkins/jobs/image-debian.yaml
- jenkins/jobs/debian: Remove stretch (EOL)
- images/debian: Remove stretch (EOL)
=> Remove Debian stretch (EOL)

images/alpine.yaml
=> images/alpine: Update mirror

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/10609
=> bin/test-lxd-network-ovn: Adds OVN load balancer tests

jenkins/jobs/image-rockylinux.yaml
=> jenkins/jobs: Add Rocky Linux 9

images/rockylinux.yaml
This is to enable version 9.0 of Rocky Linux.  Hopefully, it all looks good, if not, please flag me, email me, etc.
=> Update to Rocky Linux yaml for Version 9.0

images/ubuntu.yaml, jenkins/jobs/image-ubuntu.yaml, jenkins/jobs/lxc-build-ubuntu-source.yaml
=> Drop Ubuntu 21.10

bin/test-lxd-devlxd-vm
=> bin/test-lxd-devlxd-vm: Test instance Ready state

bin/test-lxd-devlxd-vm
=> bin/test-lxd-devlxd-vm: Fix incorrect stop invocation

jenkins/jobs/image-alpine.yaml
=> jenkins/jobs: Re-enable Alpine 3.16

bin/build-cache-lxd
=> bin/build-cache-lxd: Only download MinIO source once

bin/test-lxd-storage-buckets, jenkins/jobs/lxd-test-storage-buckets.yaml
Just a simple create/delete test for now to check its working in the snap package.
=> bin/test-lxd-storage-buckets: Add S3 storage bucket tests for snap package

bin/build-lxd
=> bin/build-lxd: Add comment regarding shiftfs being disabled

bin/test-lxd-storage-buckets
=> bin/test-lxd-storage-buckets: Fix ceph tests

jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml
=> jenkins/jobs/lxd-test-network-ovn: Use jammy

bin/test-lxd-storage-volumes-vm
Depends on https://github.com/lxc/lxd/pull/11143
=> bin/test-lxd-storage-volumes-vm: Adds test for publishing VM image

images/openeuler.yaml, jenkins/jobs/image-openeuler.yaml
Signed-off-by: lichaoran <pkwarcraft@gmail.com>
=> add openEuler-22.03-LTS and openEuler-20.03-LTS-SP3 image supports

images/openeuler.yaml
Signed-off-by: lichaoran <pkwarcraft@gmail.com>
=> switch to https://ru-repo.openeuler.org/ to let lxc jenkins work

jenkins/jobs/image-openeuler.yaml
Signed-off-by: lichaoran <pkwarcraft@gmail.com>
=> add 22.09 release

images/archlinux.yaml, images/opensuse.yaml, images/ubuntu.yaml
=> images: Make sudoers entries consistent

jenkins/jobs/image-fedora.yaml
=> jenkins/jobs: Add Fedora Rawhide

images/alpine.yaml
=> images/alpine: Attempt to fix installation errors

bin/test-lxd-cpu-vm
Requires https://github.com/lxc/lxd/pull/11262
=> Test LXD ephemeral VMs

jenkins/jobs/image-funtoo.yaml
Related to the https://github.com/lxc/distrobuilder/pull/689 align the jenkins setup.
Please, check if I don't miss anything. I'm not sure about the cd/ci workflow used at the moment.
=> images/funtoo: Add support to next release

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/11371
=> bin/test-lxd-network-ovn: Check for network forward conflicting detection on uplink

bin/test-lxd-storage-vm
Depends on https://github.com/lxc/lxd/pull/11385
=> test: VM id updated after snapshotting and storage pool copy

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/11513
=> test-lxd-network-ovn: Adds nested VLAN tests

images/openeuler.yaml, jenkins/jobs/image-openeuler.yaml
After some investigates on some of the openeuler mirror sites.
I think maybe give [aliyun mirror site](https://mirrors.aliyun.com) a try, here's the pingtest results:
=> Try with aliyun mirror site

images/openeuler.yaml
- Fix a typo,
- Switch package repo to aliyun as well.
=> also switch aliyun in post stage

bin/test-lxd-network-ovn
Requires https://github.com/lxc/lxd/pull/11686
=> bin/test-lxd-network-ovn: Adds tests for sticky DHCPv4

images/openeuler.yaml
As openEuler's first North American mirror site setup, i'd like give it a shoot :)
=> switch to mirrors.ocf.berkeley.edu

images/openwrt.yaml, jenkins/jobs/image-openwrt.yaml
see also lxc/distrobuilder#773
=> Add OpenWRT 23.05

jenkins/jobs/image-fedora.yaml
=> jenkins/jobs: Add Fedora 39

jenkins/jobs/image-nixos.yaml
I think this is what @stgraber was suggesting in https://github.com/lxc/lxc-ci/issues/786 , but if not please let me know.
Guarded to unstable for now. We will backport the necessary hydra change if everything looks good here, and then this can be updated to support both.
=> nixos: add VM images from hydra

jenkins/jobs/image-fedora.yaml
Adding fedora 40 to the jenkins build matrix. Released 4/23/24
=> feat: add fedora 40 to jenkins matrix

jenkins/jobs/image-nixos.yaml
https://nixos.org/blog/announcements/2024/nixos-2405/
=> nixos: add 24.05 release

jenkins/jobs/image-alt.yaml
=> Update releases list

images/debian.yaml
Addresses https://github.com/lxc/lxc-ci/issues/847
The specific changes were taken from `ubuntu.yaml`.
=> debian: added disk resizing

images/nixos.yaml, jenkins/jobs/image-nixos.yaml
~~Setting to draft until https://github.com/lxc/distrobuilder/pull/890 is merged.~~ Otherwise ready to go.
=> nixos: add 24.11 image

images/alpine.yaml, jenkins/jobs/image-alpine.yaml
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.21.0
=> alpine: add 3.21 and remove 3.17 EOL

images/alt.yaml
This pull request fixes the bug of not adding drivers to the kernel, and also adds symlinks to the necessary images.
=> Force adding of drivers to kernel, some links for precise indication

images/rockylinux.yaml
This would fix https://github.com/lxc/lxc-ci/issues/894
=> Add support for RockyLinux 10

images/centos.yaml, jenkins/jobs/image-centos.yaml
Tested the container image on incus and works.
=> Add Centos Stream 10
