templates/alpine.json
Please add arm64 arch for alpine linux
Signed-off-by: Alban Vidal alban.vidal@zordhak.fr
=> alpine linux: add arm64 arch

jenkins/jobs/image-opensuse.yaml
Add Leap 15.1, and remove Leap 42.3 as it has reached EOL.
=> jenkins: Update openSUSE versions

images/voidlinux.yaml
=> images: Disable TTYs and enable /dev/console on Void Linux

images/ubuntu-core.yaml
=> images: Use source.variant for Ubuntu Core

jenkins/jobs/image-fedora.yaml
=> jenkins/jobs: Remove Fedora 28 (EOL)

jenkins/jobs/image-gentoo.yaml
Cloud-init is only supported on amd64 and x86 [0].
[0] https://packages.gentoo.org/packages/app-emulation/cloud-init
=> jenkins: Disable some Gentoo cloud images

jenkins/jobs/image-alpine.yaml
Cloud-init is currently only available in the testing repo which needs
to be enabled explicitly.
=> jenkins: Don't build cloud images for Alpine

bin/build-distro
=> bin: Fix build-distro usage message

images/fedora.yaml
=> images: Override NetworkManager config on Fedora

images/gentoo.yaml
Having invalid configuration syntax in /etc/conf.d breaks
the initial network setup. (in combination with cloud-init?)
=> Configure the hostname properly for gentoo hosts.

images/gentoo.yaml
We need all 4 scripts to be added to have a complete cloud-init run on gentoo.
=> gentoo: missing cloud scripts to the default runlevel

images/debian.yaml
After fixing the shutdown issue (#4939) by masking systemd-networkd
(c63ceec4), we should also mask the systemd-networkd-wait-online
service, otherwise things that depend on network-online.target may hang
for 2 minutes until the service times out.
=> images/debian: Also mask systemd-networkd-wait-online

jenkins/jobs/image-centos.yaml
=> jenkins/jobs: Use boot variant for CentOS 8

images/oracle.yaml
This adds the AppStream repository for OL8 when building the cloud
image. This is required as the cloud-init package is in this repo.
This is blocked by https://github.com/lxc/distrobuilder/pull/255.
=> images/oracle: Fix Oracle Linux 8 cloud image

jenkins/jobs/image-alt.yaml
=> jobs: Don't build ALT Linux P9 on ppc64

images/opensuse.yaml, jenkins/jobs/image-opensuse.yaml
This removes openSUSE 15.0 as it has reached EOL.
=> Remove openSUSE 15.0

images/archlinux.yaml
Don't attempt to remove not-installed packages as this causes pacman to
fail. This also removes pciutils from the list of packages which are to
be removed. The reason being that this package is required by the base
group, and removing it will cause problems.
=> images/archlinux: Fix package section for ARM

images/fedora.yaml
This change enables the Config and Final boot stages of cloud-init on the cloud variant of the Fedora image. This is necessary for all the documented features of cloud-init to work, such as the "packages" and "runcmd" config keys.
Signed-off-by: Michael McCallister <mike@mccllstr.com>
=> Fully enable cloud-init on Fedora

bin/build-image-distrobuilder
=> bin/build-image-distrobuilder: Allow access to loop partitions

images/gentoo.yaml
This fixes the keyserver when running `distrobuilder pack-lx{c,d}`.
=> images/gentoo: Fix keyserver

images/gentoo.yaml
=> images/gentoo: Make rsync mirror configurable

images/debian.yaml
=> images/debian: Fix arm64 grub-efi package

images/archlinux.yaml
Since linux-firmware is a dependency of linux-aarch64, removing it would
remove the kernel and mkinitcpio which in turn would leave us without an
initramfs.
Therefore, only remove linux-firmware for containers.
=> images/archlinux: Only remove linux-firmware for containers

images/archlinux.yaml
Since linux-firmware is automatically removed when removing the linux
package, don't attempt to remove it a second time as this will fail.
=> images/archlinux: Don't remove linux-firmware twice

images/archlinux.yaml
On ARM machines, the preset file is named linux-<arch>.preset instead of
linux.preset.
=> images/archlinux: Choose correct linux*.preset file

images/archlinux.yaml
This excludes the fallback initramfs. It's usually not needed and
currently causes some issues when building it.
Also, use `mkinicpio -P` which simply considers all preset files.
=> images/archlinux: Exclude fallback initramfs

images/opensuse.yaml
=> images/opensuse: Fix shim for aarch64

images/centos.yaml
=> images/centos: Use NetworkManager on CentOS 7 VM

images/debian.yaml, images/ubuntu.yaml
This adds acpid to Debian and Ubuntu VM images which resolves shutdown
issues.
=> images: Add acpid to VM images

images/debian.yaml
Hopefully this is the right fix for #166 
it works for me for debian buster with cloud-init.
points of attention:
- i picked openresolv instead of resolvconf because resolvconf fails to install during the distrobuild because /etc/resolv.conf isn't an file
=> Fixing cloud-init issue with network and dns resolving setup

jenkins/jobs/image-apertis.yaml
This reverts commit d53e606371a943c635099943e44d8a6c9ceefeb5.
Currently, the only available images for v2019.3 are the rc3 ones
which we don't support.
=> Revert "jenkins/jobs: Add Apertis v2019.3"

images/gentoo.yaml
Here is my attempt at solving the problem. I was unable to create a working image on my system, distrobuilder fails with errors.
I get this output:
```
+ mv /usr/bin/gpg2 /usr/bin/gpg2.real
+ echo '#!/bin/sh'
+ echo 'exec /usr/bin/gpg2.real --keyserver keyserver.ubuntu.com "$@"'
+ chmod +x /usr/bin/gpg2
+ cp /usr/share/portage/config/repos.conf /usr/share/portage/config/repos.conf.orig
+ sed -i s#hkps://keys.gentoo.org#keyserver.ubuntu.com#g /usr/share/portage/config/repos.conf
+ sed -ri 's#(sync-uri =) .+#\1 rsync://rsync.ca.gentoo.org/gentoo-portage/#' /usr/share/portage/config/repos.conf
+ '[' -e /etc/inittab ']'
+ sed -i 's/^c[0-9]:/#\0/' /etc/inittab
+ sed -i 's/^#\(x1:.*\)/\1/' etc/inittab
+ echo pf:12345:powerwait:/sbin/halt
+ mv /usr/bin/gpg2 /usr/bin/gpg2.real
+ echo '#!/bin/sh' …
```
=> Add init script to emerge --sync at first boot.

images/gentoo.yaml
Closes #187.
Signed-off-by: Stephen Bosch <posting@vodacomm.ca>
=> Remove ACCEPT_KEYWORDS from /etc/portage/make.conf

bin/build-lxd
This setting should be kept for a bit, to make sure we don't see test regressions. After that we'll make V2 the default in dqlite and this setting can be dropped.
=> Enable dqlite engine V2 when running Jenkins tests

bin/test-lxd-ovn
Adds OVN to lxdbr0 test before external test, so we can see where intermittent failures are occurring.
=> bin/test-lxd-ovn: Reorders comms tests so that external is last

bin/test-lxd-ovn
Depends on https://github.com/lxc/lxd/pull/8095
=> bin/test-lxd-ovn: Adds external subnets and routes overlap checks

bin/test-lxd-vm
There's a few more tests to add, but this adds most of them:
Runs the following tests for dir, btrfs, lvm and zfs:
- VM create.
- VM grow on next reboot.
- VM shrink prevented.
- VM create after storage volume.size changed.
- VM create after storage volume.block.filesystem changed.
- VM create from profile with disk smaller than default VM volume size.
- VM migrate across pools with disk size larger than volume.size.
- VM migrate across pools with disk size smaller than volume.size.
- Export VM larger than default size and import (with/without volume.size set).
=> Adds test for LXD VMs

bin/test-lxd-ovn
=> bin/test-lxd-ovn: Check DHCP can be disabled selectively and instances can still start

images/debian.yaml
gpg is a requirement for the cloud-init apt module to import keys natively.
This configuration will fail without gpg:
```yaml
#cloud-config
apt:
sources:
docker.list:
source: deb [arch=amd64] https://download.docker.com/linux/debian $RELEASE stable
keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
```
Failure:
```
[71970.876146] cloud-init[242]: 2020-12-31 22:49:19,779 - util.py[WARNING]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) failed
[71972.973731] cloud-init[242]: 2020-12-31 22:49:21,876 - gpg.py[ERROR]: Failed to obtain gpg key 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
[71972.973827] cloud-init[242]: Traceback (most recent call last):
[71972.973868] cloud-init[242]:   File …
```
=> images/debian: add gpg to debian cloud variant for apt cloud-init module

bin/test-lxd-ovn
Depends on https://github.com/lxc/lxd/pull/8276
=> bin/test-lxd-ovn: Test static routes remain after network is reconfgured

images/opensuse.yaml
This fixes a few issues with the existing opensuse lxd images.
* Install `cloud-init-config-suse` explicitly. Currently `cloud-init-config-MicroOS` is being installed as a dependency to provide `/etc/cloud/cloud.cfg`, but this configuration disables some desirable modules including packages. The suse package seems to be a better choice for these images.
* Enable cloud-init config and final stages. These are disabled by default as well, and without them cloud-init loses a number of modules as configured.
* Write an empty fstab for cloud containers in order to silence the mounts module from warning.
=> images/opensuse: improve cloud-init support

bin/test-lxd-ovn-acl
=> bin/test-lxd-ovn-acl: Delete ACLs in correct order to avoid dependency blocks

bin/test-lxd-ovn-acl
Requires: https://github.com/lxc/lxd/pull/8488
=> bin/test-lxd-ovn-acl: Adds OVN port group clean up tests

bin/test-lxd-vm
Otherwise we don't fully test that publish of >10GB image can be successfully used.
This is to test the fix from https://github.com/lxc/lxd/pull/8498
=> bin/test-lxd-vm: Ensure to start VM after growing >10GB to ensure filesystem is grown

bin/test-lxd-sriov
To check unbound VFs don't cause issues with free VF detection
Test for: https://github.com/lxc/lxd/pull/8517
=> bin/test-lxd-sriov: Launch VMs first before containers

bin/test-lxd-ovn-acl
Still tests deprecated #internal and #external subjects too.
Requires https://github.com/lxc/lxd/pull/8538
=> bin/test-lxd-ovn-acl: Updates to use new @internal and @external subjects

bin/test-lxd-ovn
Having tested the OVN CI scripts in a local LXD Focal VM using the edge snap and the Focal supplied OVN packages, I've not been able to reproduce the Jenkins CI errors:
```
==> lxdbr0 to OVN gateway in project testovn
+ U3_IPV6=fd42:dc38:3278:d5c6:216:3eff:fe4d:e45d
+ echo ==> lxdbr0 to OVN gateway in project testovn
+ lxc exec u1 --project default -- ping -c1 -4 10.10.10.201
PING 10.10.10.201 (10.10.10.201) 56(84) bytes of data.
64 bytes from 10.10.10.201: icmp_seq=1 ttl=254 time=2.12 ms
--- 10.10.10.201 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 2.121/2.121/2.121/0.000 ms
+ lxc exec u1 --project default -- ping -c1 -6 fd42:4242:4242:1010::201
PING fd42:4242:4242:1010::201(fd42:4242:4242:1010::201) 56 data bytes
--- …
```
=> bin/test-lxd-ovn: Make resilient to OVN setup races

jenkins/jobs/lxd-test-cluster.yaml
=> lxd-test-cluster: Bump previous LXD to 4.12

images/centos.yaml
=> images/centos: Restrict network-device-down.service

bin/test-lxd-network-physical-macvlan
=> lxd-network-physical-macvlan: Fix for sriov VF names

images/debian.yaml
The cloud variant of the vm type currently populates the dhcp interface config. This is detrimental for assigning static IPs with cloud-init, and duplicative of cloud-init's default of dhcp on the first interface.
This PR makes the vm type behavior match the existing container type, and sets no interface config for cloud variants.
=> debian: let cloud-init manage vm interfaces

bin/test-lxd-storage-vm
=> bin/test-lxd-storage-vm: Adds tests for attached disks

bin/test-lxd-storage-vm
Requires https://github.com/lxc/lxd/pull/8813
=> VM: Add check that 9p config drive is exported readonly

bin/test-lxd-storage-vm
Depends on https://github.com/lxc/lxd/pull/8815
=> bin/test-lxd-storage-vm: Check config drive is exported readonly using virtiofs protocol

bin/test-lxd-storage-vm
=> bin/test-lxd-storage-vm: Test 9p readonly disk is infact readonly even if mounted rw

bin/test-lxd-network-ovn
=> bin/test-lxd-network-ovn: Ping linuxcontainers.org to pre-warm neighbour cache

bin/test-lxd-images
=> bin/test-lxd-images: Fail if systemd fails

images/centos.yaml
This switches to network-scripts instead of using NetworkManager. It
does so on non-cloud containers only.
=> images/centos: Switch to network-scripts on containers

images/centos.yaml
The network-scripts package is not available on CentOS 7.
=> images/centos: Only use network-scripts on CentOS 8 / 8-Stream

images/fedora.yaml
This prevents cloud-init from failing.
=> images/fedora: Add empty /etc/fstab

images/centos.yaml
=> images/centos: Install openssh-server on cloud images

images/rockylinux.yaml
=> images/rockylinux: Add openssh-server to cloud images

bin/test-lxd-images
=> bin/test-lxd-images: Show systemd failures

jenkins/jobs/image-gentoo.yaml
=> images/gentoo: Build cloud images for amd64 and i386 only

bin/test-lxd-storage-vm
Requires https://github.com/lxc/lxd/pull/8972
Related to https://github.com/lxc/lxd/issues/8958
=> bin/test-lxd-storage-vm: Test VM crash/internal error scenarios and forcefully stopping QEMU process

images/centos.yaml
=> images/centos: Use NetworkManager on CentOS 8 armhf

jenkins/jobs/image-gentoo.yaml
=> jenkins/jobs: Add Gentoo for arm64

images/opensuse.yaml
=> images: Remove busybox-gzip on openSUSE for ppc64

images/centos.yaml
=> images: Fix CentOS architecture filters

jenkins/jobs/image-gentoo.yaml
=> jenkins/jobs: Disable Gentoo/s390x systemd variant

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/9106
=> bin/test-lxd-network-ovn: Adds tests for OVN external NAT address

images/almalinux.yaml, images/centos.yaml, images/rockylinux.yaml
centos and derivatives don't have a default locale set (but for example the debian image has `en_US.utf8` set by default).
=> set missing locales for centos derivatives

bin/test-lxd-network-ovn
Adds test for bug fixed in https://github.com/lxc/lxd/pull/9167/commits/40d2315a69308550bdcb641de90a5d297a332f87
=> bin/test-lxd-network-ovn: Adds more tests

images/opensuse.yaml
=> images/opensuse: Add growpart and e2fsprogs to desktop-kde variant

images/opensuse.yaml
Since the `opensuse` user doesn't have a password, automatic screen
locking should be disabled. Otherwise, it'll ask for a password.
=> images/opensuse: Prevent automatic screen locking

jenkins/jobs/lxd-test-cluster.yaml
=> lxd-test-cluster: Update previous LXD to 4.18

images/opensuse.yaml
This package doesn't seem to exist anymore so it needs to be dropped.
=> images/opensuse: Drop busybox-gzip removal

jenkins/jobs/image-gentoo.yaml
Gentoo no longer has a default variant. We therefore need to explicitly
use `openrc`.
=> jenkins/jobs: Fix Gentoo variants

bin/test-lxd-storage-vm
And only output device size. Use more precise matching with grep
while at it.
=> bin/test-lxd-storage-volumes-vm: use simpler unit with df

bin/test-lxd-storage-vm
=> bin/test-lxd-storage-disks-vm: use GiB instead of GB

bin/build-cache, bin/test-lxd-cgroup, bin/test-lxd-gpu-container, bin/test-lxd-gpu-mig, bin/test-lxd-gpu-vm, bin/test-lxd-interception, bin/test-lxd-maas, bin/test-lxd-network, bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn, bin/test-lxd-network-ovn-acl, bin/test-lxd-network-routed, bin/test-lxd-network-sriov, bin/test-lxd-rbac, bin/test-lxd-snapd-container, bin/test-lxd-storage-disks-vm, bin/test-lxd-storage-vm, bin/test-lxd-storage-volumes-vm, bin/test-lxd-usb
The stable `jq` snap brings version 1.5 while Focal has 1.6 as deb. `apt-get install` is also quicker than `snap install`. It also removes the need to bring the old `core` snap in.
=> Install jq from apt

bin/test-lxd-cgroup, bin/test-lxd-gpu-container, bin/test-lxd-gpu-mig, bin/test-lxd-gpu-vm, bin/test-lxd-images, bin/test-lxd-interception, bin/test-lxd-kernel, bin/test-lxd-maas, bin/test-lxd-network, bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn, bin/test-lxd-network-ovn-acl, bin/test-lxd-network-routed, bin/test-lxd-network-sriov, bin/test-lxd-rbac, bin/test-lxd-storage-disks-vm, bin/test-lxd-storage-vm, bin/test-lxd-storage-volumes-vm, bin/test-lxd-usb
Otherwise the undo the waitSnapdSeed `set -x` was affecting the global context.
=> bin/test-lxd-*: use a subshell for waitSnapdSeed to isolate set +x

jenkins/jobs/image-gentoo.yaml
Arm64 builds don't have an explicit `openrc` tarball.
=> jenkins/jobs: Use empty source.variant for Gentoo arm64

images/gentoo.yaml
- images: Install dhcpcd on Gentoo
- images: Replace default with openrc in Gentoo
=> Gentoo fixes

bin/test-lxd-storage-vm
The PR https://github.com/lxc/lxc-ci/pull/421 was causing test failures locally for LVM (at least), due to the reliance on the mismatch between GiB and GB allowing (only sometimes) to account for use of the /boot partition space in the calculation of the / filesystem size.
Ultimately all these checks were supposed to be doing is to check (in a storage-driver agnostic way) that the disks are at the expected size.
By switching to looking at the block device size directly it means we don't have to wait for it to be resized by cloud-init, and we don't have to account for the /boot partition, because using `df` of the filesystem was just a proxy to the root disk's block device size, and not a reliable one at that.
=> bin/test-lxd-storage-vm: Check root disk block device size rather than filesystem size

images/alpine.yaml
This config seems to prevent `cloud-init.network-config` and `user.network-config` from being used by Alpine containers. Untested on VMs.
Verified this change still allows the default DHCP on Alpine 3.13 and 3.15 cloud variants if no network-config is defined.
I did have to build the images using distrobuilder edge, so if this repo doesn't build using that I expect this PR would have to wait.
Note that cloud-init writes nameserver config to `/etc/network/interfaces`, which Alpine doesn't seem to support. I worked around that by writing `/etc/resolv.conf` directly in `cloud-init.user-config`:
```yaml
write_files:
- content: |
nameserver 10.0.0.1
search zone.private
path: /etc/resolv.conf
```
=> images/alpine: allow cloud-init network-config

images/centos.yaml, jenkins/jobs/image-centos.yaml
Hi there !
I made a PR to edit distrobuilder to be able to generate CentOS 9 stream images.
I have also edited this repository.
I'm sorry, I never worked on Jenkins. I am then unable to edit the CI. You will have to override the `url` parameter by one of the following (taken from [here](https://mirrors.centos.org/mirrorlist?path=/9-stream/BaseOS/x86_64/iso/)) :
```
http://mirror.in2p3.fr/pub/linux/centos-stream/9-stream/BaseOS/x86_64/iso/
http://fr2.rpmfind.net/linux/centos-stream/9-stream/BaseOS/x86_64/iso/
http://centos-stream.ip-connect.info/9-stream/BaseOS/x86_64/iso/
http://mirrors.up.pt/centos-stream/9-stream/BaseOS/x86_64/iso/
http://linuxsoft.cern.ch/centos-stream/9-stream/BaseOS/x86_64/iso/
http://mirror.netsite.dk/centos-stream/9-stream/BaseOS/x86_64/iso/ …
```
=> Add centos 9 stream

images/alpine.yaml
1. Reverts my change from #439 as it breaks VM networking. Alpine does not use systemd-style interface names by default, and I was unable to get them working with the `eudev-netifnames` package. Therefore VMs need to configure `eth0`. Users will now be able to override this since lxc/distrobuilder#596. I tested both VMs and containers, both with and without `cloud-init.network-config` this time.
2. Enables sshd service on cloud VMs on boot. Containers start sshd using some other mechanism, so I would expect VMs to have it running as well. Only enabled on cloud variants since that's where [openssh is installed](https://github.com/lxc/lxc-ci/blob/13ff688ba1de1b5b270926b7fb8422769b40ae72/images/alpine.yaml#L323)
=> images/alpine: Fix VM networking and enable sshd on VMs

images/centos.yaml, images/opensuse.yaml, jenkins/jobs/image-centos.yaml, jenkins/jobs/image-opensuse.yaml
- jenkins/jobs: Drop openSUSE Leap 15.2 (EOL)
- images/opensuse: Drop openSUSE Leap 15.2 (EOL)
- jenkins/jobs: Drop CentOS 8 (EOL)
- images/centos: Drop CentOS 8 (EOL)
=> Drop openSUSE Leap 15.2 and CentOS 8

bin/test-lxd-migration
Checks that snapshots work correctly after a migration. 
Closes #445
=> bin/test-lxd-migration: Create snapshots after connectivity test.

images/centos.yaml
=> images/centos: Blacklist ipmi_si on 8-Stream

images/fedora.yaml
Fedora uses systemd to boot and NetworkManager (or systemd-networkd in
container base) to set up networking -- these replace "initscripts" and
"network-scripts".
The "dhcp-client" package is not used at all -- both systemd-networkd
and NetworkManager use different tooling to do DHCP.
All of these have been quite been quite intentionally removed from images
provided by Fedora. Don't bring them back.
Signed-off-by: Lubomir Rintel <lkundrak@v3.sk>
=> images/fedora: Do not install deprecated components

images/fedora.yaml
The initscripts package is needed as cloud-init calls the `service`
command which is provided by this package.
=> images/fedora: Re-add initscripts package for cloud images

images/pld.yaml
The C.UTF-8 locale complains about LC_MONETARY not being correct.
Switching to en_US.UTF-8 solves the issue.
=> images/pld: Fix locale issue

images/voidlinux.yaml
The mirror wants a trailing slash and when it's missing, it adds it with a redirects to HTTP and back to HTTPS:
```
$ wget -SO /dev/null https://repo-us.voidlinux.org/current//aarch64 2>&1 | grep ^Location
Location: http://repo-us.voidlinux.org/current/aarch64/ [following]
Location: https://repo-us.voidlinux.org/current/aarch64/ [following]
$ wget -SO /dev/null https://repo-us.voidlinux.org/current/aarch64/ 2>&1 | grep ^Location
```
Only aarch64 is missing the trailing slash. Drop the (harmless) double "/" while at it.
=> images/voidlinux: avoid HTTP redirects for aarch64

images/ubuntu.yaml
acpid is still shipped in Bionic's server seed [1] but is not needed (tested locally to confirm). The server team removed it later so it is not in Focal's server seed [2].
1: https://people.canonical.com/~ubuntu-archive/germinate-output/ubuntu.bionic/server.seed
2: https://people.canonical.com/~ubuntu-archive/germinate-output/ubuntu.focal/server.seed
=> ubuntu.yaml: acpid is needed on Xenial VMs only

images/ubuntu.yaml
=> ubuntu.yaml: disco and eoan are long EOL

images/ubuntu.yaml
Kernel headers are not needed most of the time and not
having them saves ~100MB on a Jammy VM.
=> ubuntu.yaml: don't pull kernel headers

jenkins/jobs/image-gentoo.yaml
The arm64 release didn't require source.variant to be set in the case of
openrc. This has now changed.
This removes the special case around arm64.
=> jenkins/jobs/gentoo: Remove arm64 special case

bin/build-lxd
=> bin/build-lxd: Don't run unit tests in cluster mode

bin/test-lxd-storage-vm
This checks whether /dev/disk/by-id was populated by QEMU.
=> bin/test-lxd-storage-vm: Check existance of /dev/disk/by-id

images/debian.yaml
This enables systemd-networkd for the bullseye, bookworm, and sid
releases.
The systemd-networkd.service is disabled for cloud images as cloud-init
will handle networking.
The polkit-1 package is needed for systemd-resolved to set the hostname.
=> images/debian: Enable networkd for bullseye, bookworm and sid

bin/test-lxd-images
Some images require CGroupV1 which cannot be satisfied by the
testserver. Therefore, these distributions cannot be tested and need
to be excluded.
=> bin/test-lxd-images: Skip CGroupV1 images

bin/test-lxd-pylxd
I noticed our MAAS VMs logged the following when running pylxd tests:
```
snap "lxd" is already installed, see 'snap help refresh'
```
So apparently the VM already had LXD installed so wasn't getting the desired version. This also explains why I couldn't reproduce the issue #10164 in manual tests using a fresh Jammy (`lxc launch images:ubuntu/jammy`) VM.
=> test-lxd-pylxd: remove LXD snap before installing from the desired channel

images/ubuntu.yaml
With https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1960633 fixed
we no longer need to pull the bigger linux-image-generic meta package
as what we need is brought in by linux-image-virtual that we already use
for non desktop flavors.
If we ever want to build Bionic desktop images, we'd need to bring
in linux-image-virtual-hwe-18.04 kernel as the GA -virtual kernel
doesn't have the required dependencies.
=> ubuntu: linux-image-virtual has what we need for desktop

images/debian.yaml
For sid/cloud, there is no need for the enp5s0.network file as
cloud-init will create one.
Also, cloud-init uses systemd-networkd which needs to be enabled.
This fixes #498.
=> images/debian: Fix IPv4 address on sid/cloud

images/debian.yaml
=> images/debian: Fix networking on bullseye/default

images/debian.yaml
Hello,
I think the network issue in #503 is not completely fixed yet byt #504 .
With fix in #504, here is my resolv.conf file :
```
root@c1:~# cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 127.0.0.53
```
As you can see, 127.0.0.53 from `systemd-resolved.service` still shows up but is not operationnal so the DNS resolution is not reliable in the container. If I disable `systemd-resolved.service`, this issue disappears.
Shouldn't we also disable this service in the template ?
Thank you!
Jean-Michel
Signed-off-by: Jean-Michel DILLY <jmdilly@adista.fr>
=> Fix DNS issue in debian/bullseye/cloud

images/debian.yaml
This removes the enp5s0.network file from the 11/cloud image. It does
not fix anything, it just clarifies that systemd-networkd isn't used.
=> debian/images: Remove systemd network file from 11/cloud

images/gentoo.yaml
=> images/gentoo: Disable systemd-binfmt.service

images/gentoo.yaml
=> images/gentoo: Disable timer instead of service file

bin/test-lxd-network
=> bin/test-lxd-network: Wait longer for sriov to come up

images/alpine.yaml, jenkins/jobs/image-alpine.yaml
- jenkins/jobs: Drop Alpine Linux 3.12 (EOL)
- images/alpine: Remove 3.12
=> Image review

jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml
OVN on jammy is busted, so revert until we can figure out what is broken in OVN and get a fix.
=> jenkins: Revert ovn tests to run on focal

bin/test-lxd-storage-vm
Since https://github.com/lxc/lxc-ci/pull/536
Also simplifies pool creation logic and deletes unused pools earlier.
=> bin/test-lxd-storage-vm: Fixes test on lvm-thin backend

images/debian.yaml
Signed-off-by: Michael Jeanson <mjeanson@efficios.com>
=> images/debian: Add riscv64 architecture support

bin/maas-run
Follow-up on https://github.com/lxc/lxd/pull/10536
=> maas-run: force TTY allocation when running test-script

images/fedora.yaml
=> images/fedora: Fix mirror URL for ppc64le and s390x

jenkins/jobs/image-voidlinux.yaml
This uses a mirror which supports IPv6.
=> jenkins/jobs/voidlinux: Update mirror

images/opensuse.yaml, jenkins/jobs/image-opensuse.yaml
- images/opensuse: Drop duplicate ifcfg-eth0 for containers
- images/opensuse: Support Leap 15.4
- jenkins/jobs/opensuse: Add Leap 15.4
=> Add openSUSE Leap 15.4

images/centos.yaml
=> images/centos: Change mirror for 7/i386

images/voidlinux.yaml
=> images/voidlinux: Fix musl repo for x86_64 and armhf

images/archlinux.yaml
This causes archlinux-keyring to be installed/updated first which should
remove any GPG related issues when installing other packages.
=> images/archlinux: Update archlinux-keyring first

images/debian.yaml
Configure the 'systemd-networkd' service to accept 'domain' and 'search'
DHCP options during network configuration. This ensures that the
'systemd-networkd' service has the same functionality as the 'ifupdown'
service and domain name resolution in LXC containers works as expected
in environments with their own DNS domains.
Signed-off-by: Maciej Delmanowski <drybjed@drybjed.net>
=> images/debian: Use search domains from DHCP

jenkins/jobs/image-alpine.yaml
In 3.16 there is a missing package which is required by alpine-base.
Until this issue has been fixed, the build will be disabled.
=> images/alpine: Temporarily disable 3.16

images/debian.yaml
Systemd listens and reacts to ACPI events.
=> debian.yaml: don't install acpid

bin/build-cache-lxd
My understanding is that binaries included in the version specific `${GOPATH}/bin` directory are available in the `${PATH}` env var when the test suite runs.
=> bin/build-cache-lxd: Build MinIO into Go 1.18 and tip cache

images/alpine.yaml
This installs the Python modules 'serial' and 'netifaces' which are
required by cloud-init but aren't installed alongside cloud-init in
the edge release.
=> images/alpine: Install cloud-init dependencies

bin/build-cache-lxd
=> bin/build-cache-lxd: Download MinIO binary to save on go cache space in tmpfs

bin/build-cache-lxd
=> bin/build-cache-lxd: Use curl instead of wget

images/ubuntu.yaml
This temporarily disables the package-pack-en package for
focal/ppc64el due to unmet dependencies.
=> images/ubuntu: Temporarily drop language-pack-en for focal/ppc64el

bin/build-cache-lxd
`--no-progress-meter` doesn't exist in Focal's version of curl apparently.
=> bin/build-cache-lxd: Support curl in Focal

bin/build-cache-lxd
=> bin/build-cache-lxd: minio download and copy into each go version's bin dir

bin/build-cache-lxd
=> bin/build-cache-lxd: Fix installation of xgettext-go

images/fedora.yaml
This updates the mirror due to connection issues with the previous one.
=> images/fedora: Update mirror

bin/test-lxd-kernel
No need to check storage buckets support for kernel tests. Also remove unused LXD_SKIP_STATIC setting.
=> bin/test-lxd-kernel: Skip storage_buckets tests

jenkins/jobs/image-rockylinux.yaml
This adds s390x and ppc64le images for Rocky Linux 9.
=> jenkins/jobs/rocky: Add s390x and ppc64le images

jenkins/jobs/image-rockylinux.yaml
This drops s390x support due to
Fatal glibc error: CPU lacks VXE support (z14 or later required)
=> images/rockylinux: Drop s390x

images/ubuntu.yaml
This doesn't fix anything but rather keeps things consistent. On
releases prior to kinetic, /etc/resolv.conf is symlinked to
/run/systemd/resolve/stub-resolv.conf. Since systemd-resolved is a
separate package on kinetic and newer releases, this symlink is not
automatically created.
This ensures /etc/resolv.conf is correctly symlinked, and therefore not
empty.
=> images/ubuntu: Symlink /etc/resolv.conf

bin/test-lxd-storage-buckets
So that the env vars in that file are exported into the test script.
=> bin/test-lxd-storage-buckets: Use eval for contents of  http://canonical-lxd.stgraber.org/config/ceph.sh

jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml
Lets see if Jammy is behaving better with OVN now (seems better locally).
Fixes #490
=> lxd-test-network-ovn: Switch to jammy

bin/test-lxd-storage-buckets
=> bin/test-lxd-storage-buckets: Set ceph.external=true for cephobject bucket support

bin/test-lxd-storage-buckets
=> bin/test-lxd-storage-buckets: Install ceph-common to get radosgw-admin command

bin/test-lxd-network-ovn
Depends on https://github.com/lxc/lxd/pull/10978
=> test-lxd-network-ovn: Adds ovn_dhcp_reservation_tests

jenkins/jobs/lxd-test-network-ovn.yaml
=> jenkins/jobs/lxd-test-network-ovn: Jammy OVN still broken, using Focal instead

jenkins/jobs/image-opensuse.yaml
Temporarily disable the openSUSE tumbleweed/cloud image for s390x due
to a package conflict.
=> jenkins/jobs: Temporarily disable openSUSE tumbleweed/cloud/s390x

bin/test-lxd-network-ovn
Requires https://github.com/lxc/lxd/pull/11049
=> bin/test-lxd-network-ovn: Adds test for using device routes when DHCP is disabled

jenkins/jobs/image-gentoo.yaml
This temporarily disables Gentoo cloud images due to unknown build
issues.
=> jenkins/jobs: Temporarily disable Gentoo cloud images

images/debian.yaml, images/gentoo.yaml, images/kali.yaml
This removes the system-binfmt.service mask as the systemd-generator now
takes care of that.
=> images: Drop systemd-binfmt mask

bin/build-distro
This increases the size of the tmpfs to 6G as 5G wasn't enough for
openEuler.
=> build-distro: increase build tmpfs to 6G and include openEuler

bin/test-lxd-storage-vm
The GiB var is used inside the shell arithmetic operatior ((..)), there is no need to quote or even use the $ prefix.
Fixes the issue introduced by commit c9e7b41aa606a75f8
=> bin/test-lxd-storage-vm: Don't quote GiB var inside arithmetic operator

images/alpine.yaml
This fixes cloud-init which complains about missing Python modules.
=> images/alpine: Add missing Python modules on 3.17

bin/test-lxd-network
- Switches to Ubuntu 22.04.
- Adds check for VM macvlan and bridged NIC multi-queue support.
- Adds check for reloading LXD not causing connectivity issues.
Depends on https://github.com/lxc/lxd/pull/11201
=> bin/test-lxd-network: Check for VM multi-queue and LXD reload support

images/openeuler.yaml, jenkins/jobs/image-openeuler.yaml
This uses the docker-http downloader for openeuler images as the
openeuler mirrors are rather unreliable.
=> images: Use docker-http for openeuler

.github/workflows/tests.yml
Please consider using the `v3` tag instead of `latest`. We expect that a new major release could break the API of the `differential-shellcheck` GitHub Action.
Related to:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/156
=> ci(lint): pin `differential-shellcheck` to `v3` tag

images/openeuler.yaml
The build failures suggest that the rpm database is broken or corrupted.
Rebuilding the database fixes the builds.
=> images/openeuler: Rebuild rpm database after unpack

bin/test-lxd-devlxd-vm
Lets try and catch any future regressions to VM nesting.
Depends on: https://github.com/lxc/lxd/pull/11188
=> bin/test-lxd-devlxd-vm: Add VM nesting test

jenkins/jobs/lxd-cloud-test.yaml, jenkins/jobs/lxd-test-devlxd-vm.yaml, jenkins/jobs/lxd-test-gpu.yaml, jenkins/jobs/lxd-test-images.yaml, jenkins/jobs/lxd-test-interception.yaml, jenkins/jobs/lxd-test-lxd-cpu-vm.yaml, jenkins/jobs/lxd-test-maas.yaml, jenkins/jobs/lxd-test-network-bridge-firewall.yaml, jenkins/jobs/lxd-test-network-ovn-acl.yaml, jenkins/jobs/lxd-test-network-ovn.yaml, jenkins/jobs/lxd-test-network-routed.yaml, jenkins/jobs/lxd-test-network-sriov.yaml, jenkins/jobs/lxd-test-network.yaml, jenkins/jobs/lxd-test-pylxd.yaml, jenkins/jobs/lxd-test-rbac.yaml, jenkins/jobs/lxd-test-snap-migration.yaml, jenkins/jobs/lxd-test-storage-disks-vm.yaml, jenkins/jobs/lxd-test-usb.yaml
Not using sudo should make it easier to cancel jobs.
=> jenkins/jobs: maas-run shouldn't need sudo

bin/test-lxd-gpu-mig
This removes the quotes around $UUIDS as they lead to UUIDx each being
a list of UUIDs instead of a single one.
=> test-lxd-gpu-mig: Drop quotes around $UUIDS

bin/test-lxd-gpu-mig
The `$UUIDS` var being a multiline list, use `sed` to print the desired line.
=> test-lxd-gpu-mig: simplify GPU UUID handling

images/alpine.yaml
The devfs service is still useful for mounting /dev/shm in containers. Without /dev/shm, Podman fails to start in Alpine LXD containers:
```
Error: failed to get new shm lock manager: failed to create 2048 locks in /libpod_lock: no such file or directory
```
=> images/alpine: Mount /dev/shm in containers to fix Podman

bin/test-lxd-network-bridge-firewall, bin/test-lxd-network-ovn, bin/test-lxd-network-routed
These tests have run fine for a while now, but recently the `test-lxd-network-bridge-firewall` test has started failing.
I setup a VM on MAAS to match the environment where this test ran and sure enough it failed.
It seems that the MAAS VMs are running **REALLY** slowly (perhaps the host is heavily loaded) and this exposed an underlying race condition due to the erroneous way we were (not) removing the netplan files.
=> Fix netplan removal race in network tests

jenkins/jobs/image-openeuler.yaml
This temporarily disables the aarch64 builds, as the docker source
always seems to pull the amd64 images.
=> images/openeuler: Temporary disable aarch64 builds

bin/test-dqlite-benchmark, jenkins/jobs/dqlite-test-benchmark.yaml
This will run the dqlite-benchmark tool on a 3-node cluster on lantea. Once for vanilla dqlite and once for disk-mode.
Both runs take 45 mins (1.5h total) and will approximately use 50GB of disk space (rough estimate).
@stgraber Should I make the `DATA_DIR` on a special drive, or is the location I've chosen fine?
=> jenkins/jobs: Add dqlite benchmark job

.github/workflows/tests.yml
release notes for [`differential-shellcheck@v4`](https://github.com/redhat-plumbers-in-action/differential-shellcheck/releases/tag/v4.0.0) - [CHANGELOG](https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/main/docs/CHANGELOG.md#v400)
=> ci: update `differential-shellcheck` to `@v4`

bin/build-distro
This fixes funtoo image builds which were failing with `no space left on
device`.
=> build_distro: Fix funtoo builds

bin/build-distro
Looking at the image build logs, what we have been seeing a lot lately
is:
```
Error: Instance not found
Error: Failed checking instance exists "local:distrobuilder-<uuid>": Instance not found
```
This PR is an attempt to find the underlying issue.
=> build_distro: Enable debug logging

bin/test-dqlite-benchmark
=> dqlite-benchmark: maas-run requires artifacts.tar.gz

jenkins/jobs/image-funtoo.yaml
This disables Funtoo/next on armhf as there is no tarball available for
this.
=> jenkins/jobs: Disable Funtoo/next on armhf

.github/workflows/tests.yml
Differential ShellCheck requires permission `security-events: write` to upload the SARIF file to GitHub successfully.
This permission might be optional for some repositories since they allow all permissions for all workflows in settings. But I wouldn't advise this setting since the best security practice is to allow only a minimal set of required permissions.
Failing SARIF upload - [logs](https://github.com/lxc/lxc-ci/actions/runs/3998352029/jobs/6860885436#step:4:31)
=> ci: Add missing permission `security-events`

images/fedora.yaml
=> images/fedora: Use temporary mirror during build only

images/fedora.yaml
This uses the Fedora 38 GPG key for Rawhide packages.
=> images/fedora: Fix Rawhide GPG key

bin/test-lxd-storage-vm
=> test: instance's `volatile.uuid.vmgenid` and QEMU's are the same

bin/build-image-lxc, bin/testbuild-clang, bin/testbuild-gcc, jenkins/jobs/lxc-github-commit.yaml, jenkins/jobs/lxc-github-pull-test.yaml
As we can see from test logs:
https://jenkins.linuxcontainers.org/job/lxc-github-pull-test/4741/arch=amd64,compiler=gcc,restrict=vm/consoleFull Message: lxc 5.0.0
...
time epoch:			1655407214 (2022-06-16T19:20:14+00:00)
supported dependencies:	AppArmor, SECCOMP, SELinux, libcap, static libcap, pam, openssl
unsupported dependencies:	liburing, libsystemd
We don't test LXC with io_uring async API.
=> lxc-github-commit/pull: test both epoll and io_uring async API

bin/test-lxd-storage-vm
Fixes failing test run on QEMU crash recovery tests.
- Checks that the VM is started successfully to lxd-agent stage after QEMU crash recovery.
- Removes unnecessary lxc exec checks.
=> bin/test-lxd-storage-vm: Adds fsfreeze before crash recovery and export tests

bin/test-lxd-storage-vm
* Test associated with https://github.com/lxc/lxd/pull/11498
TEST : 
* side loading (see here https://paste.ubuntu.com/p/6H7fW2kM9p/) and manual testing OK
=> vmgenid: check that vmgenid (in qemu.conf) is different than `volatile.uuid.generation`

images/debian.yaml, jenkins/jobs/image-debian.yaml
According to [0] Debian Buster hasn't reached EOL yet.
Fixes #725
[0] https://wiki.debian.org/LTS
=> Restore Debian Buster images

bin/build-image-lxc
Since https://github.com/lxc/lxc/commit/820d2a2b3a886ebfe46cd256ba8c320e50fcc5cd LXC commit there is a new build dependency libdbus-1-dev. So, let's install it to fix CI tests.
Failure example:
https://jenkins.linuxcontainers.org/job/lxc-github-pull-test/4769/arch=amd64,async=epoll,compiler=gcc,restrict=vm/consoleText
Related LXC PR:
https://github.com/lxc/lxc/pull/4287
=> build-image-lxc: add dbus-1 build dependency

bin/test-lxd-network-ovn
By hotplugging statically assigned nested NICs during the instance start up we were getting IP conflicts where the instance's parent NIC had already been assigned (and configured) the statically assigned IP for the nested NIC.
=> bin/test-lxd-network-ovn: Don't race dynamic port IP allocation

jenkins/jobs/image-openeuler.yaml
To fix the failed [builds](https://jenkins.linuxcontainers.org/job/image-openeuler/architecture=amd64,release=22.09,variant=cloud/398/console), remove the ` -o source.url="openeuler/openeuler:${release}` which specified only for docker downloader.
For the record, the logs:
```
+ distrobuilder --cache-dir /root/build/cache/ --timeout 7200 build-dir image.yaml rootfs -o image.serial=20230422_16:28 -o image.architecture=x86_64 -o image.release=22.09 -o image.variant=cloud -o source.url=openeuler/openeuler:22.09
time="2023-04-22T16:28:38Z" level=info msg="Downloading source"
Error: Error while downloading source: Failed to get latest release by 22.09: Failed to read url: Get "openeuler/openeuler:22.09": unsupported protocol scheme ""
```
=> fix openeuler build failed

jenkins/jobs/image-devuan.yaml
Devuan ASCII release has disappeared from the official server.
=> jenkins/jobs: Drop Devuan ASCII

images/alpine.yaml, jenkins/jobs/image-alpine.yaml
- images: Drop Alpine Linux 3.14 (EOL)
- images: Add Alpine Linux 3.18
=> Drop Alpine Linux 3.14 (EOL) and add Alpine Linux 3.18

images/plamo.yaml, jenkins/jobs/image-plamo.yaml
Plamo Linux 8.0 has been released and now supports the 8.x series of images. And we do not support the 6.x series anymore and there are no package updates, so we remove them from the build target.
* Removed configurations for 6.x.
* The "releases" specifying "7.x" have been removed, as there is no difference in the processing required for 7.x and 8.x.
=> Add Plamo Linux 8.x

bin/test-lxd-network-ovn
This reverts commit 8fa822b1511da18a88a6e194fc77bfeb7ceb2201.
The upstream image has now been fixed.
Signed-off: Thomas Parrott <thomas.parrott@canonical.com>
=> Revert "test-lxd-network-ovn: Fix dnsmasq unmask issue due to upstream changes"

images/openeuler.yaml, jenkins/jobs/image-openeuler.yaml
Notice most failed were on `release=22.03`, and we introduce `metalink` in latest `22.03 SP2` release
I doubt in Canada we don't get an expected result, so we just keep using OCF mirror in LXC case
=> remove metalink and have a try

images/openwrt.yaml
Use noop instead of comment to remove calls to `procd_add_jail` so usages inside a shell pipeline don't result in syntax errors.
https://github.com/openwrt/openwrt/commit/936df715de3d33947ce38ca232b05c2bd3ef58f1 added a call to `procd_add_jail_mount` as part of a short-circuit test. Using a comment breaks the script.
Tested in a proxmox VM
=> Fix openwrt dnsmasq/dhcp on boot

bin/test-cowsql-benchmark, jenkins/jobs/cowsql-benchmark.yaml
This job/script for now only runs the `raft-benchmark disk` tool to benchmark raw disk sequential write performance.
More benchmarks will be added in the future.
=> Add cowsql benchmark job

bin/test-cowsql-benchmark
This branch adds a couple of new benchmarks to the cowsql job:
- the "raw" file system, in which the write speed of the underlying block device is measured
- the "submit" benchmark command, in which the performance of appending raft log entries sequentially is measured
=> New cowsql benchmarks

bin/test-cowsql-benchmark
Avoid running the benchmarks against btrfs/zfs and in buffered mode, since the results already confirm that those options are slower, as expected.
=> test-cowsql-benchmark: Dial down raft-benchmark disk testing matrix

bin/maas-kernel, jenkins/jobs/cowsql-benchmark.yaml
This enables us to track performance improvements or regressions in latest kernel versions (in particular in `io_uring`-related code).
=> Run cowsql job using the latest Zabbly kernel

bin/maas-kernel
This tweaks the set of CPUs passed to the isolcpus= kernel option.
This setting is taylor-made for lantea which has 2 sockets, with 6 physical cores each, and 2 hyper threads per core.
With the CPU set in this commit the kernel won't use the second socket at all, and all those 6 physical cores can be reserved for benchmarking.
We might need to make this value dynamic in the future, and not hard-coded/tailormade, but this is good enough for now.
=> bin/maas-kernel: Tweak the cpu set passed to isolcpus=

images/openwrt.yaml
Time is provided by host anyway. This avoids a crash loop and process isolation errors.
Specifically, this deletes the symlink in /etc/rc.d that marks a service as "enabled", i.e. setting it disabled. Wildcard notation to catch potential future updates in START/STOP sequence.
See #586
=> Update openwrt.yaml - disable sysntpd service

bin/test-incus-cgroup
I noticed a typo in the last livestream.
=> test-incus-cgroup: Fix ingress test

images/centos.yaml
The old mirror has out-of-date packages therefore we need to switch to a
mirror with the latest packages.
=> images/centos: Fix mirror for 9-Stream

jenkins/jobs/image-alpine.yaml
This removes Alpine Linux 3.15 as it has reached EOL.
=> jenkins/jobs: Drop Alpine Linux 3.15 (EOL)

images/ubuntu.yaml
Fix: Ubuntu noble container netplan not being added to the image.
=> Fix: Ubuntu noble container netplan missing

bin/test-image, jenkins/jobs/image-nixos.yaml
NixOS uses the label `unstable` for the current rolling release, follow that.
Add 23.11 stable release, which due to release timing did not get the privileged container systemd generator fix.
Unstable and later releases, 24.05 and beyond, will work out of the box.
Depends on: https://github.com/lxc/distrobuilder/pull/798
Part of: https://github.com/lxc/lxc-ci/issues/786
=> nixos: add stable version, rename current to unstable

images/funtoo.yaml
* review integration with /dev/console for both Funtoo 1.4 and Funtoo Next
* enable upgrade. This fix DHCP issue of the Funtoo Next tarball and downgrade dhcpcd to version 10.0.4
=> funtoo: Review specs

images/gentoo.yaml
fix: https://github.com/lxc/lxc-ci/issues/804
=> images/gentoo: Fix missing locale-gen in musl base profile

jenkins/jobs/image-nixos.yaml
We now also expose a stable reference for the NixOS stable release VM images.
https://hydra.nixos.org/job/nixos/release-23.11/nixos.lxdVirtualMachineImage.aarch64-linux/latest/download-by-type/file/qcow2-image
https://hydra.nixos.org/job/nixos/release-23.11/nixos.lxdVirtualMachineImage.x86_64-linux/latest/download-by-type/file/qcow2-image
cc @adamcstephens 
Closes: #786
=> nixos: Add support for stable release VM images

images/debian.yaml
Hi,
This change fix build of debian for LXC in sid version. Build OK & Tested on riscv64
You can try on your side with this way : 
```
apt install -y golang-go debootstrap rsync gpg squashfs-tools git
git clone https://github.com/lxc/distrobuilder
cd distrobuilder || exit
make
wget https://raw.githubusercontent.com/lxc/lxc-ci/main/images/debian.yaml
$HOME/go/bin/distrobuilder build-lxc -o image.architecture=riscv64 -o image.release=sid debian.yaml
```
Best Regards
=> Fix debian build

images/gentoo.yaml
- Added logic to enable `dracut` use flag on openrc variant's **installkernel** package.
- Bumped the size to 6 GB. This is just a guess, but generally software getting larger and larger won't probably take long for this to not be enough.
- Updated systemd variants **installkernel** to also enable use flag for `systemd-kernel-install` - the `systemd` use flag will be renamed to `systemd-kernel-install` some time soon. This allows both to be enabled, getting cleanly through the migration phase. Rationale was that on systemd profiles the `+systemd` use flag is always enabled, causing issues when using **installkernel** and **grub**.
I could successfully build openrc and systemd vm's with this update, although I didn't try to launch them.
=> images/gentoo: vm and installkernel related updates

images/gentoo.yaml
- add "grub" use flag with openrc (I forgot this last time),
- "systemd-kernel-install" was settled with "systemd-boot" instead on systemd.
NOTE: I couldn't boot the systemd variant, but openrc fully works. I'm gonna need some time to study systemd-boot as I've never dealt with it before. However the `systemd-boot` use flag looks final, so this should still be merged **if** systemd-boot is to be used in future with systemd vm variants.
=> images/gentoo: installkernel >=20 updates

images/kali.yaml
Source: https://www.kali.org/blog/non-free-firmware-transition/
=> Kali: Add non-free-firmware

images/centos.yaml, images/fedora.yaml, images/openeuler.yaml, images/springdalelinux.yaml
Or the dracut will report the space missing error and the drivers planning added would not be added.
=> Fixed space missing around dracut add_drivers+=

images/almalinux.yaml, images/alpine.yaml, images/archlinux.yaml, images/centos.yaml, images/debian.yaml, images/fedora.yaml, images/gentoo.yaml, images/openeuler.yaml, images/opensuse.yaml, images/rockylinux.yaml, images/springdalelinux.yaml, images/ubuntu.yaml
The root partition may not be /dev/sda2, for example if set the boot disk as the second disk, the root partition device name will be /dev/sdb2. It may be /dev/vda2 if not using san disk. The fix figured out the root partition device UUID and set the UUID as the root, the root partition device UUID keeps no change.
Depends on lxc/distrobuilder#830
=> Fixed hardcoded root partition device name sda2

jenkins/jobs/image-debian.yaml
This reverts commit 7b25a9c4d239b56e7a0f0946b0eddb245f3ef6c2.  It seems to work again now.
=> Revert "debian: Disable trixie (not debootstrapable)"

images/alpine.yaml
When creating VM on incus with Alpine, I get in the logs `/var/log/cloud-init.log`:
```
- cc_resizefs.py[DEBUG]: Resizing / (ext4) using resize2fs /dev/sda2
- subp.py[DEBUG]: Running command ('resize2fs', '/dev/sda2') with allowed return codes [0] (shell=False, capture=True)
- util.py[WARNING]: Failed to resize filesystem (cmd=('resize2fs', '/dev/sda2'))
- util.py[DEBUG]: Failed to resize filesystem (cmd=('resize2fs', '/dev/sda2'))
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/cloudinit/subp.py", line 280, in subp
sp = subprocess.Popen(
^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
self._execute_child(args, executable, preexec_fn, close_fds,
File "/usr/lib/python3.11/subprocess.py", line 1955, in _execute_child
raise …
```
=> add: e2fsprogs-extra to Alpine cloud

images/nixos.yaml
Fixes #831 - `/etc/nixos/configuration.nix` is generated upstream and still refers to `lxd.nix` under that name.
=> Revert change to name of generated .nix include file for now

images/gentoo.yaml
Remove GPG workaround as redundant.
Remove changing RSYNC_MIRROR commands as effectively noop. Add ability to use binary packages when possible. Remove redundant portage files after installation (source files, binary packages, portage tree).
=> Gentoo template update

images/openeuler.yaml
Connectivity from builders to the primary mirror has been flaky:
```
+ distrobuilder --cache-dir /root/build/cache/ --timeout 7200 build-dir image.yaml rootfs -o image.serial=20240906_18:19 -o image.architecture=aarch64 -o image.release=24.03 -o image.variant=default time="2024-09-06T18:19:22Z" level=info msg="Downloading source" Error: Error while downloading source: Failed to download https://repo.openeuler.org/openEuler-24.03-LTS/ISO/aarch64/openEuler-24.03-LTS-aarch64-dvd.iso: stream error: stream ID 7; INTERNAL_ERROR; received from peer time="2024-09-06T18:47:35Z" level=error msg="Failed running distrobuilder" err="Error while downloading source: Failed to download https://repo.openeuler.org/openEuler-24.03-LTS/ISO/aarch64/openEuler-24.03-LTS-aarch64-dvd.iso: stream error: stream ID …
```
=> openeuler: Switch to Berkeley OCF mirror

jenkins/jobs/image-fedora.yaml
Fedora 41 Released 10/29/24
https://fedoramagazine.org/announcing-fedora-linux-41/
=> jenkins: Build Fedora 41 Imgaes

images/openwrt.yaml
https://discuss.linuxcontainers.org/t/openwrt-images-dont-generate-ula-prefix/22561
=> Update openwrt.yaml - add ula_prefix to network config

images/openeuler.yaml
This reverts commit 7358d9f4ebb0a30233aaee56ad4513dc2e226819.
The Berkeley OCF mirror is currently missing files and 404ing for paths like https://mirrors.ocf.berkeley.edu/openeuler/openEuler-24.03-LTS-SP1/ISO/aarch64/openEuler-24.03-LTS-SP1-aarch64-dvd.iso
=> Revert "openeuler: Switch to Berkeley OCF mirror"

images/debian.yaml
- polkit is needed for systemd-networkd to set hostnames
- this operation can happen in an Incus container based on `images:debian/trixie/cloud`
```
$ incus create images:debian/trixie/cloud nettest
```
Then in container:
```
$ journalctl -u systemd-networkd
Jan 28 19:51:40 nettest systemd-networkd[189]: eth1: Gained IPv6LL
Jan 28 19:51:40 nettest systemd-networkd[189]: eth2: Gained IPv6LL
Jan 28 19:51:40 nettest systemd-networkd[189]: eth2: DHCPv4 address 192.168.254.28/24, gateway 192.168.254.1 acquired from 192.168.254.1
Jan 28 19:51:43 nettest systemd-networkd[189]: Could not set hostname: Access denied
```
Looks like polkit needs to be added back for trixie. Once the package is installed the error is gone.
IMHO this does need to be in place for both container and VM as in both …
=> debian: add polkit for trixie

images/alt.yaml
This pull request adds instructions to the yaml file to add the ability to create virtual machines based on the ALT Linux distribution using Distrobuilder.
At the moment, the alt.yaml file only contains instructions for building a container.
=> ALT Linux vm support

images/gentoo.yaml
Summary from the Gentoo News item:
"Starting with version 106 of sys-kernel/dracut the default for the "hostonly" setting has changed from disabled to enabled when Dracut is invoked via installkernel.
"hostonly" is a setting for Dracut that controls how much is included in the generated initramfs image. When it is disabled Dracut aims to generate an initramfs image that is bootable on any hardware. On the other hand, when this setting is enabled, Dracut aims to generate an initramfs image containing only what is needed to boot the current system. The advantage is a significantly smaller initramfs images, but this comes with the cost of losing portability."
dracut-ng/dracut-ng#1158
https://www.gentoo.org/support/news-items/2025-02-03-dracut-hostonly.html
Note:
- This change is relevant …
=> images/gentoo.yaml: prepare for dracut-106's hostonly change

jenkins/jobs/image-alt.yaml
This PR adds code to jenkins job for building Alt virtual mashines, the support of which was added in the `793300b` commit.
=> Add jenkins job for building Alt vm

jenkins/jobs/image-alt.yaml
This PR removes building of p10 platform of Alt Linux. It is not supported no more.
=> Remove Alt P10 release from jenkins jobs

images/alt.yaml
This PR adds 'sg' driver to kernel in Alt distribution to try running it from images.linuxcontainers.org.
=> Add sg driver to kernet in Alt distribution

bin/test-image
Context: https://discuss.linuxcontainers.org/t/sharing-directory-with-debian-13-vm-does-not-work/23361
=> test-image: fix typo causing the script to fail silently

.github/workflows/commits.yml, deps/lxc-exercise
Re-enable:
- lxc-test-apparmor-mount
- lxc-test-autostart
- lxc-test-unpriv
- lxc-test-usernic
- lxc-test-state-server
back as they pass without any problems.
Keep `lxc-test-no-new-privs` test disabled as it is still broken.
Requires https://github.com/lxc/lxc/pull/4549
=> deps/lxc-exercise: re-enable some tests

deps/lxc-exercise
We should re-enable this one too.
Simon Deziel (<simon.deziel@canonical.com>) was doing an independent investigation of another failures with LXD and it turned out that [1] introduces lxc exec command regressions.
Also, this commit breaks lxc-test-no-new-privs test which was disabled for a while since we migrated from Jenkins self-hosted runners to a GitHub Actions ones.
[1] https://github.com/lxc/lxc/commit/50dee37cfe3201ed51f477356f81941c960a5511
=> deps/lxc-exercise: re-enable lxc-test-no-new-privs

images/alpine.yaml
gcc was added to vm variant in commit aa865878c798 (images/alpine: Add Alpine VM support) but there was no explanation why it is needed. Nothing uses it and it is also more or less useless without libc headers. Remove it.
This reduces the size with 61%. (from 253MB to 97MB)
=> alpine: remove needless install of gcc in vm

images/alpine.yaml
We don't need both hwdrivers/mdev and udev-*. Remove udev as mdev is enough for incus VMs.
=> alpine: remove udev in vm

images/alpine.yaml
We don't need to explicitly load sd-mod or usb-storage to find the root file system in initramfs. Remove those from boot option modules.
=> alpine: drop unneeded modules from grub config

bin/test-incus-network-ovn
Renames the incus projects in the incus ovn tests to make them distinct from the network names.
=> rename incus ovn test projects

images/almalinux.yaml, jenkins/jobs/image-almalinux.yaml
The container image works (at least for `default`, I did not test `cloud`).
Regarding the VM image :
- it boots fine (but I don't understand why the approach used for v9 cannot be adapted for v10 -- I took the code from @MichaelStauber's version which works)
- however the agent does not start
At the end of boot, console shows:
```
[    9.036680] virtio-fs: tag <config> not found
[   14.317760] virtio-fs: tag <config> not found
[   19.396814] virtio-fs: tag <config> not found
[   24.647583] virtio-fs: tag <config> not found
[   29.897760] virtio-fs: tag <config> not found
[   35.140829] virtio-fs: tag <config> not found
[   40.395432] virtio-fs: tag <config> not found
[   45.644483] virtio-fs: tag <config> not found
[   50.893362] virtio-fs: tag <config> not found
```
The changes should …
=> Add image generation for AlmaLinux 10

images/debian.yaml
Enable UseMTU option in the systemd-networkd configuration so the MTU option injected by ie. an Incus OVN network gets applied to the NIC.
=> debian: use DHCPv4 MTU option

images/centos.yaml
Latest build [failed](https://jenkins.linuxcontainers.org/job/image-centos/3917/architecture=amd64,release=10-Stream,variant=default/console) when trying to run the grubby command. That package is still available on [C9](https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/Packages/) & [C10](https://mirror.stream.centos.org/10-stream/BaseOS/x86_64/os/Packages/), just not explicitly brought in neither by the deps nor the base image.
Also fixed networking setup scripts, since we don't use dhclient on C10 anymore.
=> Centos: Fixes for post-files scripts

jenkins/jobs/image-debian.yaml
At this time, the armhf images produced for both Debian trixie and Debian forky seem functional.
=> Re-enable armhf images for Debian trixie and Debian forky
